name: Publish Fabric and Forge Releases

on:
  push:
    branches:
      - main

jobs:
  publish_releases:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'adopt'

    - name: Check commit message
      id: check_commit_message
      run: echo "commit_starts_with_version=$(echo "${{ github.event.head_commit.message }}" | grep -c '^version')" >> "$GITHUB_OUTPUT"

    - name: Build with Gradle
      if: steps.check_commit_message.outputs.commit_starts_with_version == '1'
      run: |
        chmod +x ./gradlew
        ./gradlew build

    - name: Get project version
      if: steps.check_commit_message.outputs.commit_starts_with_version == '1'
      id: get_version
      run: echo "version=$(grep -oP 'mod\.version=\K(.+)' ./gradle.properties)" >> "$GITHUB_OUTPUT"

    - name: Create Fabric release
      if: steps.check_commit_message.outputs.commit_starts_with_version == '1'
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: "v${{ steps.get_version.outputs.version }}-fabric"
        name: "Fabric v${{ steps.get_version.outputs.version }}"
        body: |
          Release for Fabric version ${{ steps.get_version.outputs.version }}
        draft: false
        prerelease: false

    - name: Create Forge release
      if: steps.check_commit_message.outputs.commit_starts_with_version == '1'
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: "v${{ steps.get_version.outputs.version }}-forge"
        name: "Forge v${{ steps.get_version.outputs.version }}"
        body: |
          Release for Forge version ${{ steps.get_version.outputs.version }}
        draft: false
        prerelease: false
